### ISSUE TITLE
Can't build array library.

### ISSUE THREAD

**Issue by master-q** [ajhc/ajhc#3]
Can't build array library.

```
$ ajhc --build-hl array.yaml
ajhc --build-hl array.yaml
ajhc 0.8.0.1 (830a6f81207bac4394f8981e3f432821358d862b)
Creating library from description file: "array.yaml"
Reading: "array.yaml"
Finding Dependencies...
Using Ho Cache: '/home/kiwamu/.ajhc/cache'
./Data/Array/Base.hs:119:39: Invalid Class. multiparameter classes not yet supported
```

Need to build below yaml file.

``` yaml
Name:            array
Version:         0.4.0.1
Synopsis:        Mutable and immutable arrays
hs-source-dir:   .
include-dirs:    include
include-sources: include/Typeable.h
exposed-modules:
      - Data.Array
      - Data.Array.Base
      - Data.Array.IArray
      - Data.Array.IO
      - Data.Array.IO.Safe
      - Data.Array.IO.Internals
      - Data.Array.MArray
      - Data.Array.MArray.Safe
      - Data.Array.ST
      - Data.Array.ST.Safe
      - Data.Array.Storable
      - Data.Array.Storable.Safe
      - Data.Array.Storable.Internals
      - Data.Array.Unboxed
      - Data.Array.Unsafe
extensions:
      - CPP
      - MultiParamTypeClasses,
      - FlexibleContexts,
      - FlexibleInstances,
      - TypeSynonymInstances
      - DeriveDataTypeable,
      - StandaloneDeriving,
      - Rank2Types,
      - MagicHash,
      - UnboxedTuples,
      - ForeignFunctionInterface,
      - UnliftedFFITypes
```
