### ISSUE TITLE
Can't build vector library.

### ISSUE THREAD

**Issue by master-q** [ajhc/ajhc#5]
Can't build vector library with below yaml file.

``` yaml
Name:           vector
Version:        0.10.0.1
Synopsis:       Efficient Arrays
Extensions:     [ CPP, DeriveDataTypeable ]
Exposed-Modules:
        - Data.Vector.Internal.Check
        - Data.Vector.Fusion.Util
        - Data.Vector.Fusion.Stream.Size
        - Data.Vector.Fusion.Stream.Monadic
        - Data.Vector.Fusion.Stream
        - Data.Vector.Generic.Mutable
        - Data.Vector.Generic.Base
        - Data.Vector.Generic.New
        - Data.Vector.Generic
        - Data.Vector.Primitive.Mutable
        - Data.Vector.Primitive
        - Data.Vector.Storable.Internal
        - Data.Vector.Storable.Mutable
        - Data.Vector.Storable
        - Data.Vector.Unboxed.Base
        - Data.Vector.Unboxed.Mutable
        - Data.Vector.Unboxed
        - Data.Vector.Mutable
        - Data.Vector
Include-Dirs:
        - include
        - internal
Include-Sources: vector.h
Build-Depends:   deepseq
```

The error is....

```
$ ajhc --build-hl vector.yaml
ajhc --build-hl vector.yaml
ajhc 0.8.0.1 (830a6f81207bac4394f8981e3f432821358d862b)
Creating library from description file: "vector.yaml"
Reading: "vector.yaml"
Finding Dependencies...
Using Ho Cache: '/home/kiwamu/.ajhc/cache'
./Data/Vector.hs:220:6: Parse error
$ vi ./Data/Vector.hs
   1 {-# LANGUAGE FlexibleInstances
   2            , MultiParamTypeClasses
   3            , TypeFamilies
   4            , Rank2Types
   5            , BangPatterns
   6   #-}
--snip--
 213 instance Data a => Data (Vector a) where
 214   gfoldl       = G.gfoldl
 215   toConstr _   = error "toConstr"
 216   gunfold _ _  = error "gunfold"
 217   dataTypeOf _ = G.mkType "Data.Vector.Vector"
 218   dataCast1    = G.dataCast
 219 
 220 type instance G.Mutable Vector = MVector
 221 
 222 instance G.Vector Vector a where
 223   {-# INLINE basicUnsafeFreeze #-}
 224   basicUnsafeFreeze (MVector i n marr)
 225     = Vector i n `liftM` unsafeFreezeArray marr
```
